const REQUEST_PING = 1000
const REQUEST_REPLAY = 1001
const REQUEST_TRANSACTION = 1002

const RESPONSE_PONG = 2000
const RESPONSE_REPLAY = 2001
const RESPONSE_TRANSACTION = 2002

const PUSH_TRANSACTION = 3000

export default {
  REQUEST_PING,
  REQUEST_REPLAY,
  REQUEST_TRANSACTION,
  RESPONSE_PONG,
  RESPONSE_REPLAY,
  RESPONSE_TRANSACTION,
  PUSH_TRANSACTION
}
